language: node_js

node_js:
- '8'
- '10'

sudo: false

before_script:
- npm install
- npm install -g coveralls lerna
- lerna bootstrap --hoist --no-ci

script:
- ./node_modules/.bin/jest --coverage
- cat ./coverage/lcov.info | coveralls
