language: node_js

node_js:
- '8'
- '10'

sudo: false

cache:
  directories:
  - 'node_modules'

before_script:
- npm install
- npm install -g coveralls lerna
- lerna bootstrap --hoist --no-ci

script:
- ./node_modules/.bin/jest --coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
